### ISSUE TITLE
Problem with OSXPeripheral class on Mac OS X 10.10.5 (MacBook Pro (Retina, 15-inch, Early 2013)

### ISSUE THREAD

**Issue by eadward** [brettchien/PyBLEWrapper#2]
I am using some Python code that uses PyBLEWrapper to interface bluetooth devices. Unfortunately I am having some problems, and I was wondering whether you can help. Below the error I am getting. Thank you!

`---------------------------------------------------------------------------
BadPrototypeError                         Traceback (most recent call last)
<ipython-input-27-40e671b9b51c> in <module>()
----> 1 bleCollectWaveforms(duration=120)
      2 
      3 #waveformSignalFeature
      4 print 'Total OpticalData', len(WaveformSignal.getOpticalData())
      5 print 'Total AccelerometerData', len(WaveformSignal.getAccelerometerData())

<ipython-input-25-89dd91a7ad0f> in bleCollectWaveforms(duration, collectOptical, collectAccelerometer)
      3     global waveformSignalFeature
      4     #Doug's Scanner
----> 5     cm = pyble.CentralManager()
      6     print 'cm.ready:',  cm.ready
      7 

/Users/eadward/anaconda/lib/python2.7/site-packages/pyble/__init__.pyc in __new__(cls, *args, **kwargs)
     43         system = platform.system()
     44         if system == "Darwin":
---> 45             from .osx.centralManager import OSXCentralManager
     46             return OSXCentralManager.alloc().init()
     47         elif system == "Linux":

/Users/eadward/anaconda/lib/python2.7/site-packages/pyble/osx/centralManager.py in <module>()
      4 
      5 from pyble._roles import Central, Peripheral
----> 6 from peripheral import OSXPeripheral
      7 
      8 import logging

/Users/eadward/anaconda/lib/python2.7/site-packages/pyble/osx/peripheral.py in <module>()
     22 
     23 @Trace
---> 24 class OSXPeripheral(NSObject, Peripheral):
     25     """
     26     Connected Peripheral

BadPrototypeError: Objective-C expects 1 arguments, Python argument has 2 arguments for <unbound selector findServiceByCharacteristicInstance of OSXPeripheral at 0x11143fc60>`

**Comment by brettchien** [comment]
Sorry it takes so long that I can finally address this issue.

I was thinking this issue is related to nsobject and python class multiple inheritance.
In the end, there's a **Backword compatibility note** mention in the PyObjC 3.2
that a python_method descriptor needs to be added for pure python function in ObjC class.
[PyObjC 3.2 Changelog](https://pythonhosted.org/pyobjc/core/changelog.html)

I have updated source codes, but not yet reflect to pypi.
Please pip directly from the source.
