### ISSUE TITLE
Setting characteristic Notify value doesn't do anything

### ISSUE THREAD

**Issue by tisaacs** [brettchien/PyBLEWrapper#3]
Hello,

I'm trying to send and receive data from a bluetooth LE device on OSX.
I can connect and send data following the `example.py` file, however when I try to subscribe to notifications on a characteristic nothing appears to happen.

Specifically, `rx.notify = True` runs without exception but when I query the `rx.notify` value it returns `False`. `rx` is a characteristic object.

I've also tried to run the `peripheral.setNotifyForCharacteristic(True, rx)` function but get the following exception:
```
ValueError: NSInvalidArgumentException - Class OC_PythonObject: no such selector: peripheral
```
Do you have any suggestions?

Your help is appreciated.

Many thanks,
Toby

**Comment by brettchien** [comment]
You may want to try the peripheral on Lightblue or similar App to verify the peripheral is working.

Just do a quick check, 
1. the peripheral should have notification cability, I think it should be already there.
   Please check with other App to see if peripheral is working as expected, like LightBlue
2. the notify property is not updated after the notify is enabled, this is a bug should be fix.
    you still be able to get notifications from the peripherals
3. you can try to use ```peripheral.setNotifyForCharacteristic(True, rx.instance)```, the second parameter needs to take the actual ObjectC object, wrapped in the the characteristic object

I am not using this project in production, it may take some times for me to solve this.

Glad to know someone is using it.

**Comment by tisaacs** [comment]
Thanks for the prompt reply.

With regards to your 3 points:
1. Notification capability is working with our android and iOS app so the peripheral is fine - we're using the library for automated testing.

2. Brilliant, completely understand it'll take a while.

3. I'll try this.

We've actually also tried writing a swift native app after filing the issue and it looks like we're run into a similar problem so it looks like it might be an issue with the OS.

**Comment by brettchien** [comment]
If your native swift app cannot receive notification then this wrapper cannot receive such notification, this wrapper is also based on the same framework.

I thought the iOS and OSX framework shares the same interface, the result should be consistent.

**Comment by tisaacs** [comment]
Yeah we didn't try until after I'd filed the issue. 
I think the issue is with the OSX stack - the code is identical to iOS but it works on iOS. 

Thanks again for your help.
